ihlt : server.h ConnectionsDoublyLinkedList.o protocol.o server.o guardian.o

ConnectionsDoublyLinkedList.o : ConnectionsDoublyLinkedList.h

protocol.o : protocol.h

guardian.o : guardian.h

clean:
	rm -f *.o ihlt

.PHONY: clean
